### ISSUE TITLE
[Suggestion] Set object models directory

### ISSUE THREAD

**Issue by Vasily-X** [Papawy/Papawyconv#1]
Hello, this is a suggestion: I'd allow to set a directory for the artconfig.txt lines. I mean something like this: `"mydirectory/generated.dff", "mydirectory/generated.txd"`.

`convert --ide file.ide --ipl file.ipl --dir mydirectory`

When the `AddSimpleModel` lines are generated where does the second parameter come from? Is that the original object ID?

Regards.

**Comment by Papawy** [comment]
I don't really understand your first suggestion. You want to have something like `AddSimpleModel(vw, id, id, "mydir/model.dff", "mydir/model.txd");` ?

The second parameter (19379 right ?) is an ID of an existing object I've set because I didn't really know what to put. It's supposed to be a valid object ID which the added object will inherit from but I can't determine it with an IDE or an IPL file.

**Comment by Papawy** [comment]
Done in next release.
